"""modification2

Revision ID: 00968d4e4331
Revises: 649d7006ae26
Create Date: 2026-03-26 09:55:05.554767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00968d4e4331'
down_revision: Union[str, Sequence[str], None] = '649d7006ae26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('client', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaries', 'client')
    # ### end Alembic commands ###
