"""modification3

Revision ID: 28253cd2ed25
Revises: 00968d4e4331
Create Date: 2026-03-26 10:13:03.212001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28253cd2ed25'
down_revision: Union[str, Sequence[str], None] = '00968d4e4331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'salaries',
    'num_securite_sociale',
    type_=sa.Integer(),
    postgresql_using='num_securite_sociale::integer'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salaries', 'num_securite_sociale',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
