"""ajout facture

Revision ID: 29bee5e98e69
Revises: b28f6f6f7ddd
Create Date: 2026-04-02 11:14:08.609376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bee5e98e69'
down_revision: Union[str, Sequence[str], None] = 'b28f6f6f7ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('jours_travailles', sa.Integer(), nullable=True))
    op.add_column('factures', sa.Column('tjm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'tjm')
    op.drop_column('factures', 'jours_travailles')
    # ### end Alembic commands ###
