"""notification

Revision ID: 2a2e6a12ea74
Revises: e3cf6715d4ba
Create Date: 2026-04-29 09:24:04.527143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2e6a12ea74'
down_revision: Union[str, Sequence[str], None] = 'e3cf6715d4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('niveau', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('recommandation', sa.String(), nullable=True),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('projet_nom', sa.String(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
