"""projet_historiquecorrection

Revision ID: 396495dd8d6a
Revises: 29bee5e98e69
Create Date: 2026-04-03 10:06:11.108906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396495dd8d6a'
down_revision: Union[str, Sequence[str], None] = '29bee5e98e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historique_salarie', sa.Column('projet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'historique_salarie', 'projet', ['projet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historique_salarie', type_='foreignkey')
    op.drop_column('historique_salarie', 'projet_id')
    # ### end Alembic commands ###
