"""modif

Revision ID: 4f55da3f0e61
Revises: a0a07e445a2f
Create Date: 2026-04-02 09:12:17.089548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f55da3f0e61'
down_revision: Union[str, Sequence[str], None] = 'a0a07e445a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('historique_salarie_salarie_id_fkey'), 'historique_salarie', type_='foreignkey')
    op.create_foreign_key(None, 'historique_salarie', 'salaries', ['salarie_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projet', 'salarie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('projet_salarie_id_fkey'), 'projet', type_='foreignkey')
    op.create_foreign_key(None, 'projet', 'salaries', ['salarie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projet', type_='foreignkey')
    op.create_foreign_key(op.f('projet_salarie_id_fkey'), 'projet', 'salaries', ['salarie_id'], ['id'])
    op.alter_column('projet', 'salarie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'historique_salarie', type_='foreignkey')
    op.create_foreign_key(op.f('historique_salarie_salarie_id_fkey'), 'historique_salarie', 'salaries', ['salarie_id'], ['id'])
    # ### end Alembic commands ###
