"""modification

Revision ID: 649d7006ae26
Revises: fc19dd3ac04c
Create Date: 2026-03-26 09:42:23.746753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649d7006ae26'
down_revision: Union[str, Sequence[str], None] = 'fc19dd3ac04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('marge_cible', sa.Float(), nullable=True))
    op.add_column('projet', sa.Column('champ_remarque', sa.String(), nullable=True))
    op.add_column('projet', sa.Column('salarie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projet', 'salaries', ['salarie_id'], ['id'])
    op.drop_column('projet', 'jours_travailles')
    op.add_column('salaries', sa.Column('adresse', sa.String(), nullable=True))
    op.add_column('salaries', sa.Column('num_securite_sociale', sa.String(), nullable=True))
    op.drop_column('salaries', 'projet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('projet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('salaries', 'num_securite_sociale')
    op.drop_column('salaries', 'adresse')
    op.add_column('projet', sa.Column('jours_travailles', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projet', type_='foreignkey')
    op.drop_column('projet', 'salarie_id')
    op.drop_column('projet', 'champ_remarque')
    op.drop_column('projet', 'marge_cible')
    # ### end Alembic commands ###
