"""modification5

Revision ID: 6972df50b09f
Revises: adc3c2c66115
Create Date: 2026-03-26 12:00:12.726470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6972df50b09f'
down_revision: Union[str, Sequence[str], None] = 'adc3c2c66115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('email', sa.String(), nullable=False))
    op.add_column('salaries', sa.Column('date_entree', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'salaries', ['email'])
    op.drop_column('salaries', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'salaries', type_='unique')
    op.drop_column('salaries', 'date_entree')
    op.drop_column('salaries', 'email')
    # ### end Alembic commands ###
