"""projetmodif

Revision ID: 6ea67b1f6f65
Revises: 98139885d3cf
Create Date: 2026-04-16 10:18:30.830598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea67b1f6f65'
down_revision: Union[str, Sequence[str], None] = '98139885d3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projet', 'tjm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'projet', ['nom'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projet', type_='unique')
    op.alter_column('projet', 'tjm',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
