"""client et facture

Revision ID: 7118d2414f5b
Revises: c39e14dbc11d
Create Date: 2026-04-01 11:30:05.749855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7118d2414f5b'
down_revision: Union[str, Sequence[str], None] = 'c39e14dbc11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Nom du client'),
    sa.Column('code_client', sa.String(length=24), nullable=True, comment='Code client unique'),
    sa.Column('client', sa.String(length=1), nullable=True, comment='1=Client, 2=Prospect'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='Nom du fichier logo'),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Téléphone'),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True, comment='Site web'),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('zip', sa.String(length=25), nullable=True, comment='Code postal'),
    sa.Column('town', sa.String(length=50), nullable=True, comment='Ville'),
    sa.Column('country_code', sa.String(length=2), nullable=True, comment='Code ISO pays (FR, GB…)'),
    sa.Column('idprof1', sa.String(length=20), nullable=True, comment='SIRET (14 chiffres)'),
    sa.Column('idprof2', sa.String(length=20), nullable=True, comment='SIREN'),
    sa.Column('idprof3', sa.String(length=20), nullable=True, comment='Code NAF / APE'),
    sa.Column('tva_intra', sa.String(length=20), nullable=True, comment='N° TVA intracommunautaire'),
    sa.Column('forme_juridique', sa.String(length=100), nullable=True, comment='SAS, SARL, SA…'),
    sa.Column('capital', sa.Float(), nullable=True, comment='Capital social en €'),
    sa.Column('effectif', sa.String(length=10), nullable=True, comment='Tranche effectif'),
    sa.Column('date_creation', sa.BigInteger(), nullable=True),
    sa.Column('date_modification', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=30), nullable=False, comment='Référence facture (ex: FA2024-0001)'),
    sa.Column('socid', sa.Integer(), nullable=False, comment='ID du client (llx_societe)'),
    sa.Column('date', sa.BigInteger(), nullable=True, comment="Date d'émission"),
    sa.Column('date_lim_reglement', sa.BigInteger(), nullable=True, comment="Date d'échéance"),
    sa.Column('date_creation', sa.BigInteger(), nullable=True, comment='Date de création'),
    sa.Column('date_validation', sa.BigInteger(), nullable=True, comment='Date de validation'),
    sa.Column('total_ht', sa.Float(), nullable=True, comment='Montant HT'),
    sa.Column('total_tva', sa.Float(), nullable=True, comment='Montant TVA'),
    sa.Column('total_ttc', sa.Float(), nullable=True, comment='Montant TTC'),
    sa.Column('sumpayed', sa.Float(), nullable=True, comment='Déjà payé'),
    sa.Column('resteapayer', sa.Float(), nullable=True, comment='Reste à payer'),
    sa.Column('paye', sa.String(length=1), nullable=True, comment='0=Non payée, 1=Payée'),
    sa.Column('statut', sa.String(length=1), nullable=True, comment='0=Brouillon, 1=Validée/En attente, 2=Clôturée'),
    sa.Column('online_payment_url', sa.String(length=255), nullable=True, comment='URL de paiement en ligne'),
    sa.ForeignKeyConstraint(['socid'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factures')
    op.drop_table('Clients')
    # ### end Alembic commands ###
