"""projects

Revision ID: 8a69348dc662
Revises: 2a2e6a12ea74
Create Date: 2026-05-17 17:46:28.819088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a69348dc662'
down_revision: Union[str, Sequence[str], None] = '2a2e6a12ea74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # 1 ajouter colonne nullable=True
    op.add_column(
        'projet',
        sa.Column('client_id', sa.Integer(), nullable=True)
    )

    # 2 créer foreign key
    op.create_foreign_key(
        'fk_projet_client',
        'projet',
        'Clients',
        ['client_id'],
        ['id']
    )

    # 3 si tu veux affecter un client par défaut
    # exemple : client id = 1
    op.execute("""
        UPDATE projet
        SET client_id = 1
        WHERE client_id IS NULL
    """)

    # 4 rendre obligatoire
    op.alter_column(
        'projet',
        'client_id',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projet', type_='foreignkey')
    op.drop_column('projet', 'client_id')
    # ### end Alembic commands ###
