"""role_sal

Revision ID: 98139885d3cf
Revises: 396495dd8d6a
Create Date: 2026-04-08 09:45:17.925911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98139885d3cf'
down_revision: Union[str, Sequence[str], None] = '396495dd8d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salaries', 'role', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('salaries', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'salaries', type_='foreignkey')
    op.drop_column('salaries', 'role_id')
    # ### end Alembic commands ###
