"""ajouthistorqiue

Revision ID: a646e45019ea
Revises: 6972df50b09f
Create Date: 2026-03-30 12:03:14.447061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a646e45019ea'
down_revision: Union[str, Sequence[str], None] = '6972df50b09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_salarie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salarie_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('joursTravailles', sa.Float(), nullable=True),
    sa.Column('paye', sa.Integer(), nullable=True),
    sa.Column('tjm', sa.Float(), nullable=True),
    sa.Column('salaireBrut', sa.Float(), nullable=True),
    sa.Column('netAvantImpot', sa.Float(), nullable=True),
    sa.Column('netPayer', sa.Float(), nullable=True),
    sa.Column('chargesPatronales', sa.Float(), nullable=True),
    sa.Column('facture', sa.Integer(), nullable=True),
    sa.Column('repasRestaurant', sa.Float(), nullable=True),
    sa.Column('totalCotisationsSalariales', sa.Float(), nullable=True),
    sa.Column('totalNoteFrais', sa.Float(), nullable=True),
    sa.Column('totalNoteKilometrique', sa.Float(), nullable=True),
    sa.Column('totalePercu', sa.Float(), nullable=True),
    sa.Column('totaleFacture', sa.Float(), nullable=True),
    sa.Column('salaireNetHorsRepas', sa.Float(), nullable=True),
    sa.Column('rentabilite', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salarie_id'], ['salaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_salarie_id'), 'historique_salarie', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historique_salarie_id'), table_name='historique_salarie')
    op.drop_table('historique_salarie')
    # ### end Alembic commands ###
