"""modification4

Revision ID: adc3c2c66115
Revises: 28253cd2ed25
Create Date: 2026-03-26 11:17:00.610077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc3c2c66115'
down_revision: Union[str, Sequence[str], None] = '28253cd2ed25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salaries', 'num_securite_sociale',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salaries', 'num_securite_sociale',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
