"""suppresionmodif

Revision ID: e3cf6715d4ba
Revises: 6ea67b1f6f65
Create Date: 2026-04-17 14:23:50.620199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cf6715d4ba'
down_revision: Union[str, Sequence[str], None] = '6ea67b1f6f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('historique_salarie_salarie_id_fkey'), 'historique_salarie', type_='foreignkey')
    op.drop_constraint(op.f('historique_salarie_projet_id_fkey'), 'historique_salarie', type_='foreignkey')
    op.create_foreign_key(None, 'historique_salarie', 'salaries', ['salarie_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'historique_salarie', 'projet', ['projet_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('projet_salarie_id_fkey'), 'projet', type_='foreignkey')
    op.create_foreign_key(None, 'projet', 'salaries', ['salarie_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projet', type_='foreignkey')
    op.create_foreign_key(op.f('projet_salarie_id_fkey'), 'projet', 'salaries', ['salarie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'historique_salarie', type_='foreignkey')
    op.drop_constraint(None, 'historique_salarie', type_='foreignkey')
    op.create_foreign_key(op.f('historique_salarie_projet_id_fkey'), 'historique_salarie', 'projet', ['projet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('historique_salarie_salarie_id_fkey'), 'historique_salarie', 'salaries', ['salarie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
