"""create tab project

Revision ID: f9e692575bb0
Revises: c5aaa6eb8061
Create Date: 2026-03-13 12:34:48.038871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e692575bb0'
down_revision: Union[str, Sequence[str], None] = 'c5aaa6eb8061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('jours_travaillés', sa.Integer(), nullable=True),
    sa.Column('tjm', sa.Integer(), nullable=True),
    sa.Column('status_paiement', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projet')
    # ### end Alembic commands ###
