"""change

Revision ID: fc19dd3ac04c
Revises: f9e692575bb0
Create Date: 2026-03-15 22:29:12.242552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc19dd3ac04c'
down_revision: Union[str, Sequence[str], None] = 'f9e692575bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('jours_travailles', sa.Integer(), nullable=True))
    op.drop_column('projet', 'jours_travaillés')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('jours_travaillés', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('projet', 'jours_travailles')
    # ### end Alembic commands ###
